import React from 'react';
import { View, Text, ScrollView, StyleSheet } from 'react-native';
import TopBar from '../components/TopBar';

export default function PrivacyPolicy({ navigation }) {
  return (
    <View style={styles.container}>
      <TopBar title="Privacy Policy" onBack={() => navigation.goBack()} />
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        <Text style={styles.updateDate}>Last Updated: July 12, 2026</Text>

        <Text style={styles.paragraph}>
          kedulz ("we", "us", or "our") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, store, and safeguard your information when you use our mobile application and website, and what control you have over it.
        </Text>

        <Text style={styles.paragraph}>
          <Text style={styles.bold}>Please read this Privacy Policy carefully.</Text> By accepting our Terms and Conditions, you explicitly consent to the data practices described in this policy.
        </Text>

        <Text style={styles.heading}>1. Information We Collect</Text>

        <Text style={styles.subheading}>1.1 Personal Information You Provide</Text>
        <Text style={styles.paragraph}>
          <Text style={styles.bold}>For All Users:</Text>{'\n'}
          • Identity Information: Full name, date of birth, age, gender{'\n'}
          • Contact Information: Mobile number, email address{'\n'}
          • Location Information: Address, city, state, PIN code, country{'\n'}
          • Login PIN: Set by you and end-to-end encrypted (see Section 5)
        </Text>

        <Text style={styles.paragraph}>
          <Text style={styles.bold}>For Patients:</Text>{'\n'}
          • Health vital signs (height, weight, blood pressure, heart rate, etc.){'\n'}
          • Blood group and medical conditions{'\n'}
          • Current medications and drug allergies{'\n'}
          • Medical history and family medical history{'\n'}
          • Appointment and prescription information{'\n'}
          • Family member information you choose to add
        </Text>

        <Text style={styles.paragraph}>
          <Text style={styles.bold}>For Doctors:</Text>{'\n'}
          • Medical specialization and designation{'\n'}
          • Medical registration/license number{'\n'}
          • Workplace details (clinic/hospital information){'\n'}
          • Consultation hours and availability
        </Text>

        <Text style={styles.subheading}>1.2 Information Automatically Collected</Text>
        <Text style={styles.paragraph}>
          • Device type, model, and operating system{'\n'}
          • Unique device identifiers{'\n'}
          • App usage data and navigation patterns{'\n'}
          • GPS location (when searching for nearby doctors){'\n'}
          • Push notification device tokens{'\n'}
          • Error logs and crash reports
        </Text>

        <Text style={styles.heading}>2. How We Use Your Information</Text>
        <Text style={styles.paragraph}>
          We use your information to:{'\n\n'}
          <Text style={styles.bold}>Service Delivery:</Text>{'\n'}
          • Create and manage your account{'\n'}
          • Facilitate appointment booking{'\n'}
          • Share relevant medical details with the doctor you book, so they can triage and treat you accurately{'\n'}
          • Send appointment reminders and updates{'\n'}
          • Generate and securely store your digital prescriptions{'\n\n'}
          <Text style={styles.bold}>Communication:</Text>{'\n'}
          • Send push notifications about appointments{'\n'}
          • Respond to support requests{'\n'}
          • Send service announcements{'\n\n'}
          <Text style={styles.bold}>Improvement:</Text>{'\n'}
          • Analyze usage patterns{'\n'}
          • Fix technical issues{'\n'}
          • Develop new features
        </Text>

        <Text style={styles.heading}>3. Information Sharing and Disclosure</Text>
        <Text style={styles.paragraph}>
          We do NOT sell, rent, or share your personal information with third parties for marketing or advertising purposes. Your information is shared only in the following limited circumstances:{'\n\n'}
          <Text style={styles.bold}>With your treating doctor:</Text> When you book an appointment, relevant medical information (such as vitals, history, medications, and allergies) is shared with that specific doctor solely so they can triage and consult you effectively. This access is limited to doctors you have actively booked with.{'\n\n'}
          <Text style={styles.bold}>Prescriptions:</Text> Prescriptions generated by a doctor are visible only to you and that doctor. They are not shared with any other party.{'\n\n'}
          <Text style={styles.bold}>Legal requirements:</Text> Where required by law, regulation, court order, or legal process.{'\n\n'}
          <Text style={styles.bold}>With your explicit consent:</Text> If you separately and knowingly authorize us to share specific information.{'\n\n'}
          We do not otherwise disclose your personal or medical information to any other user, doctor, advertiser, or third party.
        </Text>

        <Text style={styles.heading}>4. Your Control Over Your Data</Text>
        <Text style={styles.paragraph}>
          You are always in control of your information. Within the app, you can:{'\n\n'}
          • View all personal and medical information we hold about you{'\n'}
          • Edit or correct your information at any time{'\n'}
          • Remove family member profiles you have added{'\n'}
          • Delete your account and associated data{'\n'}
          • Opt out of push notifications{'\n'}
          • Disable location services{'\n\n'}
          Note: Finalized prescriptions and certain appointment records may be retained even after account deletion, where required for legal, medical record-keeping, or regulatory purposes.
        </Text>

        <Text style={styles.heading}>5. Data Security</Text>
        <Text style={styles.paragraph}>
          We implement industry-standard security measures to protect your information:{'\n\n'}
          • All personal and medical data is stored in a secure, encrypted database{'\n'}
          • Your login PIN is end-to-end encrypted — it is never stored in readable form and is not accessible to kedulz, our employees, or any third party{'\n'}
          • Encryption of data in transit and at rest{'\n'}
          • Secure authentication and authorization controls{'\n'}
          • Regular security audits and access monitoring{'\n'}
          • Secure cloud infrastructure
        </Text>

        <Text style={styles.warningBox}>
          ⚠️ No method of transmission over the internet is 100% secure. While we implement strong safeguards, including end-to-end encryption of your login PIN, we cannot guarantee absolute security.
        </Text>

        <Text style={styles.heading}>6. Prescriptions</Text>
        <Text style={styles.paragraph}>
          Prescriptions are generated in real time by your treating doctor at the time of consultation and are stored securely in our database. A prescription is a private medical record shared only between you and the issuing doctor — kedulz does not use this content beyond safely storing and making it available to you.
        </Text>

        <Text style={styles.heading}>7. Your Rights and Choices</Text>
        <Text style={styles.paragraph}>
          You have the right to:{'\n\n'}
          • Access your personal information{'\n'}
          • Update or correct your information{'\n'}
          • Delete your account{'\n'}
          • Opt out of push notifications{'\n'}
          • Disable location services{'\n'}
          • Withdraw consent (where applicable), noting this may limit your ability to use certain features
        </Text>

        <Text style={styles.heading}>8. Data Retention</Text>
        <Text style={styles.paragraph}>
          We retain your information for as long as necessary to provide the Service and comply with legal and medical record-keeping obligations. When you delete your account, we delete or anonymize your personal information, except for records (such as finalized prescriptions) that we are legally required to retain.
        </Text>

        <Text style={styles.heading}>9. Children's Privacy</Text>
        <Text style={styles.paragraph}>
          Our Service is not intended for children under 18 without parental or guardian consent. We do not knowingly collect information from children under 18 without such consent. If you believe we have collected such information improperly, please contact us so we can address it.
        </Text>

        <Text style={styles.heading}>10. Changes to This Privacy Policy</Text>
        <Text style={styles.paragraph}>
          We may update this Privacy Policy from time to time. We will notify you of any material changes by updating the "Last Updated" date and through the Service.
        </Text>

        <Text style={styles.heading}>11. Contact Us</Text>
        <Text style={styles.paragraph}>
          If you have questions about this Privacy Policy or wish to exercise any of your rights, please contact us:{'\n\n'}
          Email: privacy@kedulz.com{'\n'}
          Website: https://kedulz.com{'\n'}
          Address: kedulz, India
        </Text>

        <View style={styles.bottomSpace} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  updateDate: {
    fontSize: 12,
    color: '#7f8c8d',
    marginBottom: 16,
    fontStyle: 'italic',
  },
  heading: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2c3e50',
    marginTop: 24,
    marginBottom: 12,
  },
  subheading: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34495e',
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontSize: 14,
    color: '#2c3e50',
    lineHeight: 22,
    marginBottom: 12,
  },
  bold: {
    fontWeight: '700',
  },
  warningBox: {
    backgroundColor: '#fff3cd',
    borderLeftWidth: 4,
    borderLeftColor: '#ff9800',
    padding: 16,
    marginVertical: 16,
    borderRadius: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#856404',
  },
  bottomSpace: {
    height: 40,
  },
});
